 &id1 !!org.kalibro.Configuration
name: "SC configuration"
description: "Sample configuration with natives cbo, lcom4 and compound sc."
metricConfigurations:
  - &id2 !!org.kalibro.MetricConfiguration
    aggregationForm: AVERAGE
    baseTool: null
    code: "sc"
    metric: &id3 !!org.kalibro.CompoundMetric
      description: ""
      name: "Structural Complexity"
      scope: CLASS
      script: "return cbo * lcom4"
    ranges: []
    readingGroup: null
    weight: 1.0
  - &id4 !!org.kalibro.MetricConfiguration
    aggregationForm: AVERAGE
    baseTool: &id5 !!org.kalibro.BaseTool
      collectorClassName: "inexistent.Class"
      description: "Base tool for testing"
      name: "Inexistent"
      supportedMetrics:
        - &id6 !!org.kalibro.NativeMetric
          description: ""
          languages:
            - C
            - CPP
            - JAVA
          name: "Coupling Between Objects"
          scope: CLASS
        - &id7 !!org.kalibro.NativeMetric
          description: ""
          languages:
            - C
            - CPP
            - JAVA
          name: "Lack of Cohesion of Methods"
          scope: CLASS
        - &id8 !!org.kalibro.NativeMetric
          description: ""
          languages:
            - C
            - CPP
            - JAVA
          name: "Total Coupling Factor"
          scope: SOFTWARE
    code: "cbo"
    metric: *id6
    ranges: []
    readingGroup: null
    weight: 1.0
  - &id9 !!org.kalibro.MetricConfiguration
    aggregationForm: AVERAGE
    baseTool: *id5
    code: "lcom4"
    metric: *id7
    ranges:
      - &id10 !!org.kalibro.Range
        beginning: 0.0
        comments: ""
        end: 1.0
        reading: &id11 !!org.kalibro.Reading
          color: 0x00ff00
          grade: 10.0
          label: "Good"
      - &id12 !!org.kalibro.Range
        beginning: 1.0
        comments: ""
        end: .inf
        reading: &id13 !!org.kalibro.Reading
          color: 0xff0000
          grade: 0.0
          label: "Bad"
    readingGroup: &id14 !!org.kalibro.ReadingGroup
      name: "Extremes"
      description: "All or nothing group."
      readings:
        - *id13
        - *id11
    weight: 1.0
  - &id15 !!org.kalibro.MetricConfiguration
    aggregationForm: AVERAGE
    baseTool: *id5
    code: "total_cof"
    metric: *id8
    ranges: []
    readingGroup: null
    weight: 1.0