---
serviceSide: SERVER # CLIENT to connect to Kalibro Service; SERVER if the service is running on this machine

clientSettings:
  serviceAddress: "http://localhost:8080/KalibroService/" # Address of the remote Kalibro Service

mailSettings:
  smtpHost: "smtp.gmail.com"
  smtpPort: 465
  senderMail: "example@gmail.com"
  password: "securepassword" # This password shall be stored securely in the future

serverSettings:
  loadDirectory: ~/.kalibro/repositories # Source code will be loaded in this directory before analysis
  databaseSettings:
    databaseType: MYSQL # Possibilities: APACHE_DERBY, MYSQL
    jdbcUrl: "jdbc:mysql://localhost:3306/kalibro"
    username: "kalibro"
    password: "kalibro"