 &id1 !!org.kalibro.KalibroSettings
serviceSide: SERVER # CLIENT to connect to Kalibro Service; SERVER if the service is running on this machine

clientSettings: &id2 !!org.kalibro.ClientSettings
  serviceAddress: "http://localhost:8080/KalibroService/" # Address of the remote Kalibro Service

mailSettings: &id3 !!org.kalibro.MailSettings
  smtpHost: "smtp.gmail.com"
  smtpPort: 465
  senderMail: "example@gmail.com"
  password: "examplepassword"

serverSettings: &id4 !!org.kalibro.ServerSettings
  loadDirectory: ~/.kalibro/projects # Source code will be loaded in this directory before analysis
  databaseSettings: &id5 !!org.kalibro.DatabaseSettings
    databaseType: POSTGRESQL # Possibilities: MYSQL, POSTGRESQL, SQLITE
    jdbcUrl: "jdbc:postgresql://localhost:5432/kalibro"
    username: "kalibro"
    password: "kalibro"