code: lcom4
metric: &id1 !!org.kalibro.NativeMetric
  name: "Lack of Cohesion of Methods"
  scope: CLASS
  languages:
    - C
    - CPP
    - JAVA
baseTool:
  name: "Inexistent"
  description: "Base tool for testing"
  collectorClassName: "inexistent.Class"
  supportedMetrics:
    - !!org.kalibro.NativeMetric
      name: "Coupling Between Objects"
      scope: CLASS
      languages:
        - C
        - CPP
        - JAVA
    - *id1
weight: 1.0
aggregationForm: AVERAGE
readingGroup:
  name: "Extremes"
  description: "All or nothing group."
  readings:
    - &id2
      color: 0xff0000
      grade: 0.0
      label: "Bad"
    - &id3
      color: 0x00ff00
      grade: 10.0
      label: "Good"
ranges:
  -
    beginning: 0.0
    end: 1.0
    reading: *id3
  -
    beginning: 1.0
    end: .inf
    reading: *id2