package org.kalibro.core.concurrent;

/**
 * A report which indicates that a {@link Task} has finished. This report is generated by a task when it finishes
 * (normally or throwing an exception). The report is passed to every {@link TaskListener} object that registered to
 * receive such reports using the {@code Task.addListener} method.
 * 
 * @author Carlos Morais
 */
public class TaskReport<T> {

	private Task task;
	private long executionTime;

	private T result;
	private Throwable error;

	protected TaskReport(Task task, long executionTime, T result, Throwable error) {
		this.task = task;
		this.executionTime = executionTime;
		this.result = result;
		this.error = error;
	}

	public Task getTask() {
		return task;
	}

	public long getExecutionTime() {
		return executionTime;
	}

	public boolean isTaskDone() {
		return error == null;
	}

	public Object getResult() {
		return result;
	}

	public Throwable getError() {
		return error;
	}
}